### ISSUE TITLE
Infinite loop in parallel evaluation

### ISSUE THREAD

**Issue by mottosso** [mgear-dev/Data-centric_rigging_sample_data#1]
Hi all,

I get semi-consistent freezes of Maya with this rig (`girl_Outfit_A_film.ma`) when Maya is in parallel evaluation mode. *Semi*-consistent, because it happens each time, but during different circumstances.

For example:

1. 10 seconds after referencing, displaying the missing file path node in the attribute editor
2. 2 minutes in, during playback of some animation on her hip

In each case, one core is pegged at 100% which leads me to believe there's a divide by zero or infinite loop happening somewhere. I tried narrowing down the number of custom nodes used, but there are a lot. I attempted to delete `mgear_squashAndStretch2` nodes, as they likely contain some division, but much of the rig seems built on it so it wasn't easy to continue testing without it.

The same action, and 30-40 minutes of continous use in Serial and I didn't experience any lockups.

Is there any node in particular you suspect could be the culprit? Have you encountered this before?

**Comment by miquelcampos** [comment]
Hello @mottosso 

that is strange. the rigs are very simple.  I will check it ASAP.  Maybe the fife has something funky. 

The other rigs don't have any issues?

Thanks for the feedback! :)

**Comment by mottosso** [comment]
> The other rigs don't have any issues?

I only tried this one, but I figured they were all the same but with different geometry?

I can continue trying to narrow down the issue if you help me pinpoint any particular node you think is especially suspect?

**Comment by miquelcampos** [comment]
nothing, in particular, is special about the rigs or models

**Comment by mottosso** [comment]
Not special necessarily, but I suspect the loop happens in one of these custom nodes:

![image](https://user-images.githubusercontent.com/2152766/100612228-8c367200-330a-11eb-99c5-5d222e27146e.png)

Is there any of these you suspect could be the culprit? Or, any of these that are most likely not the problem?

**Comment by miquelcampos** [comment]
we use these nodes for production every day and didn't find that issue until now.

**Comment by miquelcampos** [comment]
but maybe a divide by zero?? the squash node was creating that issue. But not to the point of crashing or infinite loop

we recently did an update for that one https://github.com/mgear-dev/mgear_solvers/pull/6

**Comment by mottosso** [comment]
I've been trying to reproduce the problem in with a few hours of use with this rig and couldn't. Threading issues are the worst. :( It's quite possible there never was a problem with the rig, that it was elsewhere. I'll continue using the rig and will revisit this if/when it happens once again.

**Comment by miquelcampos** [comment]
@mottosso thanks for letting me know :)
